import pandas as pd
from _typeshed import Incomplete

from . import cache as cache
from . import utils as utils
from .config import YfConfig as YfConfig
from .data import YfData as YfData
from .exceptions import (
    YFDataException as YFDataException,
)
from .exceptions import (
    YFEarningsDateMissing as YFEarningsDateMissing,
)
from .exceptions import (
    YFRateLimitError as YFRateLimitError,
)
from .live import WebSocket as WebSocket
from .scrapers.analysis import Analysis as Analysis
from .scrapers.fundamentals import Fundamentals as Fundamentals
from .scrapers.funds import FundsData as FundsData
from .scrapers.history import PriceHistory as PriceHistory
from .scrapers.holders import Holders as Holders
from .scrapers.quote import FastInfo as FastInfo
from .scrapers.quote import Quote as Quote

class TickerBase:
    ticker: Incomplete
    session: Incomplete
    ws: Incomplete
    def __init__(self, ticker, session=None) -> None: ...
    @utils.log_indent_decorator
    def history(self, *args, **kwargs) -> pd.DataFrame: ...
    def get_recommendations(self, as_dict: bool = False): ...
    def get_recommendations_summary(self, as_dict: bool = False): ...
    def get_upgrades_downgrades(self, as_dict: bool = False): ...
    def get_calendar(self) -> dict: ...
    def get_sec_filings(self) -> dict: ...
    def get_major_holders(self, as_dict: bool = False): ...
    def get_institutional_holders(self, as_dict: bool = False): ...
    def get_mutualfund_holders(self, as_dict: bool = False): ...
    def get_insider_purchases(self, as_dict: bool = False): ...
    def get_insider_transactions(self, as_dict: bool = False): ...
    def get_insider_roster_holders(self, as_dict: bool = False): ...
    def get_info(self) -> dict: ...
    def get_fast_info(self): ...
    def get_sustainability(self, as_dict: bool = False): ...
    def get_analyst_price_targets(self) -> dict: ...
    def get_earnings_estimate(self, as_dict: bool = False): ...
    def get_revenue_estimate(self, as_dict: bool = False): ...
    def get_earnings_history(self, as_dict: bool = False): ...
    def get_eps_trend(self, as_dict: bool = False): ...
    def get_eps_revisions(self, as_dict: bool = False): ...
    def get_growth_estimates(self, as_dict: bool = False): ...
    def get_earnings(self, as_dict: bool = False, freq: str = "yearly"): ...
    def get_income_stmt(self, as_dict: bool = False, pretty: bool = False, freq: str = "yearly"): ...
    def get_incomestmt(self, as_dict: bool = False, pretty: bool = False, freq: str = "yearly"): ...
    def get_financials(self, as_dict: bool = False, pretty: bool = False, freq: str = "yearly"): ...
    def get_balance_sheet(self, as_dict: bool = False, pretty: bool = False, freq: str = "yearly"): ...
    def get_balancesheet(self, as_dict: bool = False, pretty: bool = False, freq: str = "yearly"): ...
    def get_cash_flow(
        self, as_dict: bool = False, pretty: bool = False, freq: str = "yearly"
    ) -> pd.DataFrame | dict: ...
    def get_cashflow(self, as_dict: bool = False, pretty: bool = False, freq: str = "yearly"): ...
    def get_dividends(self, period: str = "max") -> pd.Series: ...
    def get_capital_gains(self, period: str = "max") -> pd.Series: ...
    def get_splits(self, period: str = "max") -> pd.Series: ...
    def get_actions(self, period: str = "max") -> pd.Series: ...
    def get_shares(self, as_dict: bool = False) -> pd.DataFrame | dict: ...
    @utils.log_indent_decorator
    def get_shares_full(self, start=None, end=None): ...
    def get_isin(self) -> str | None: ...
    def get_news(self, count: int = 10, tab: str = "news") -> list: ...
    def get_earnings_dates(self, limit: int = 12, offset: int = 0) -> pd.DataFrame | None: ...
    def get_history_metadata(self) -> dict: ...
    def get_funds_data(self) -> FundsData | None: ...
    def live(self, message_handler=None, verbose: bool = True) -> None: ...
