from _typeshed import Incomplete

class NestedConfig:
    def __init__(self, name, data) -> None: ...
    def __getattr__(self, key): ...
    def __setattr__(self, key, value) -> None: ...
    def __len__(self) -> int: ...

class ConfigMgr:
    def __init__(self) -> None: ...
    def __getattr__(self, key): ...
    def __contains__(self, key) -> bool: ...

YfConfig: Incomplete
