name: Master branch checks

on:
  push:
    branches:
      - master
      - "v*.*.*"
    tags:
      - "v*.*.*"
  pull_request:
  workflow_dispatch:


jobs:
  checks:
    uses: ./.github/workflows/shared.yaml